FROM python:3.9

WORKDIR /backend

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Create a directory for the SQLite database
RUN mkdir -p /backend/data && chmod 777 /backend/data

# We don't need to copy the application code here
# as it will be mounted as a volume

# Set the Python path
ENV PYTHONPATH=/backend

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]