FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# We don't need to copy the application code here
# as it will be mounted as a volume

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]