# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Install bash
RUN apt-get update && apt-get install -y bash

# Make port 80 available to the world outside this container
EXPOSE 80

# Set the default command to bash
# CMD ["/bin/bash"]
CMD ["python", "openaigpt.py"]